name: DockerImage build and push

on:
  workflow_dispatch:
  push:
    tags: '*'

env:
  ECR_REPO: 305587085711.dkr.ecr.us-west-2.amazonaws.com/bnb-chain

jobs:
  # Push image to GitHub Packages.
  push-op-node:
    runs-on: ["self-hosted", "linux", "x64", "ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 305587085711.dkr.ecr.us-west-2.amazonaws.com
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_ACCESS_KEY }}
      - name: image meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.ECR_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=op-node-,format=short
            type=raw,value=op-node-latest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./op-node/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
